In [145]:
import pandas as pd
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import root_mean_squared_error, mean_absolute_percentage_error, r2_score
from sklearn.linear_model import LinearRegression, LassoCV, RidgeCV, ElasticNetCV, Lasso
from sklearn.preprocessing import StandardScaler
import numpy as np

In [146]:
df = pd.read_csv("./nyc_taxi_preprocessed.csv")

In [147]:
df.head()

,vendor_id,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration,day_of_week,hour_of_day
0,2,-73.953918,40.778873,-73.963875,40.771164,0,400,0,16
1,1,-73.988312,40.731743,-73.994751,40.694931,0,1100,4,23
2,2,-73.997314,40.721458,-73.948029,40.774918,0,1635,6,17
3,2,-73.961670,40.759720,-73.956779,40.780628,0,1141,1,9
4,1,-74.017120,40.708469,-73.988182,40.740631,0,848,2,6

In [148]:
X = df.drop("trip_duration", axis=1)
y = np.log1p(df["trip_duration"])

In [149]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

### Basic Decision Tree Regressor Model

In [150]:
DT_reg_model = DecisionTreeRegressor(random_state=42)

In [151]:
DT_reg_model.fit(x_train, y_train)

DecisionTreeRegressor(random_state=42)

In [152]:
y_pred = DT_reg_model.predict(x_test)

In [153]:
root_mean_squared_error(y_test, y_pred), mean_absolute_percentage_error(y_test, y_pred), r2_score(y_test, y_pred)

(0.6114268359277305, 0.064386365677375, 0.3976642291370901)

In [ ]:
root_mean_squared_error(y_test, y_pred), mean_absolute_percentage_error(y_test, y_pred), r2_score(y_test, y_pred)

(6172.559624332101, 0.7811145244857748, -0.414860328049963)

### Linear Regression Model

In [19]:
lr_model = LinearRegression()

In [20]:
lr_model.fit(x_train, y_train)

LinearRegression()

In [21]:
y_pred = lr_model.predict(x_test)

In [23]:
root_mean_squared_error(y_test, y_pred), mean_absolute_percentage_error(y_test, y_pred)

(3167.9238392577463, 1.6537542867345025)

### Applying normalization

In [38]:
std_normalization = StandardScaler()
x_train_scaled = std_normalization.fit_transform(x_train)
x_test_scaled = std_normalization.transform(x_test)

### DT Regressor on scaled data

In [39]:
dt_model_regressor = DecisionTreeRegressor().fit(x_train_scaled, y_train)

In [40]:
y_pred = dt_model_regressor.predict(x_test_scaled)

In [41]:
root_mean_squared_error(y_test, y_pred), mean_absolute_percentage_error(y_test, y_pred)

(7381.95382799709, 0.9156811035290766)

#### oops! after scaling, the error rate is increased

### LR on scaled data

In [43]:
lr_model = LinearRegression().fit(x_train_scaled, y_train)

In [44]:
y_pred = lr_model.predict(x_test_scaled)

In [45]:
root_mean_squared_error(y_test, y_pred), mean_absolute_percentage_error(y_test, y_pred)

(3122.7279423114423, 1.6554099546160088)

#### Not significant change in the error rate

### Applying normalization didn't help in building a better model

### Updating the DT model hyperparameters

In [154]:
# List of max_depth values 
max_depth_list = list(range(25,3,-3))
max_depth_list

[25, 22, 19, 16, 13, 10, 7, 4]

In [155]:
train_score = {}
test_score = {}
for d in max_depth_list:
    dt_model = DecisionTreeRegressor(max_depth=d, random_state=42)
    dt_model.fit(x_train, y_train)
    train_score[d] = mean_absolute_percentage_error(y_train, dt_model.predict(x_train))
    test_score[d] = mean_absolute_percentage_error(y_test, dt_model.predict(x_test))

In [156]:
for d in max_depth_list:
    print("Max Dept: {0} | Train score: {1} | Test score: {2}".format(d, train_score[d], test_score[d]))

Max Dept: 25 | Train score: 0.023575390877836017 | Test score: 0.05975057628946163
Max Dept: 22 | Train score: 0.034710529364837886 | Test score: 0.058524208055136764
Max Dept: 19 | Train score: 0.04568559814553942 | Test score: 0.05860495089263412
Max Dept: 16 | Train score: 0.055700866077420384 | Test score: 0.06132119032658737
Max Dept: 13 | Train score: 0.06379783009132145 | Test score: 0.06567621012038759
Max Dept: 10 | Train score: 0.07176685362173688 | Test score: 0.07208076305554219
Max Dept: 7 | Train score: 0.08042833488272619 | Test score: 0.08023351548410447
Max Dept: 4 | Train score: 0.08591885327178246 | Test score: 0.08557610382094238

#### Comparing the output with the mean

In [ ]:
y_pred = y_test * [np.mean(y_test)]

In [ ]:
mean_absolute_percentage_error(y_test, y_pred)

-935148.081590377

In [157]:
# Dictionary to store the train and test r square scores

train_scores = {}
test_scores = {}

# Fill the values in the below list and assign value to the variable!
min_sample_leaf_list = list(range(5, 15, 2))
depth = 16

# Loop through min_sample_leaf values and train the models
for min_sample_leaf in min_sample_leaf_list:
    
    # Initialize the Decision Tree model with the current min_samples_leaf value
    DT_model = DecisionTreeRegressor(min_samples_leaf=min_sample_leaf, max_depth=depth, random_state=42)
    
    # Train the model
    DT_model.fit(x_train, y_train)
    
    # Make predictions on the train dataset
    y_train_pred = DT_model.predict(x_train)

    # Make predictions on the test dataset
    y_test_pred = DT_model.predict(x_test)
    
    # Store the train r square score in the dictionary with the min_sample_leaf as the key
    train_scores[min_sample_leaf] = mean_absolute_percentage_error (y_train, y_train_pred)
    
    # Store the test r square score in the dictionary with the min_sample_leaf as the key
    test_scores[min_sample_leaf] = mean_absolute_percentage_error (y_test, y_test_pred)

In [158]:
# Print the train and test r square scores for each model
for min_sample_leaf in min_sample_leaf_list:
    print(f"min_sample_leaf = {min_sample_leaf}|\
    Train Score = {train_scores[min_sample_leaf]:.3f} |\
    Test Score = {test_scores[min_sample_leaf]:.3f}")
    print('_'*65)

min_sample_leaf = 5|    Train Score = 0.057 |    Test Score = 0.061
_________________________________________________________________
min_sample_leaf = 7|    Train Score = 0.057 |    Test Score = 0.061
_________________________________________________________________
min_sample_leaf = 9|    Train Score = 0.058 |    Test Score = 0.061
_________________________________________________________________
min_sample_leaf = 11|    Train Score = 0.058 |    Test Score = 0.061
_________________________________________________________________
min_sample_leaf = 13|    Train Score = 0.058 |    Test Score = 0.061
_________________________________________________________________

### Applying regularization

In [121]:
# create an array with 20 numbers equllay spaced between 0 to 10
alphas = np.linspace(0, 10, 20)
alphas

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [122]:
# Initialize LassoCV to find the best alpha
lasso_cv = LassoCV(alphas= alphas,
                   cv=10, 
                   max_iter=100000)

In [123]:
lasso_cv.fit(x_train, y_train)

c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.300e+05, tolerance: 2.863e+01
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.299e+05, tolerance: 2.862e+01
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.295e+05, tolerance: 2.856e+01
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.301e+05, tolerance: 2.863e+01
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.302e+05, tolerance: 2.864e+01
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\base.py:1336: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.445e+05, tolerance: 3.180e+01
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(

LassoCV(alphas=array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ]),
        cv=10, max_iter=100000)

In [131]:
# Find the best alpha value
best_alpha = lasso_cv.alpha_
best_alpha

np.float64(0.0)

In [132]:
# Compare the coefficients before and after L2 regularization
coefficients_after_l1 = pd.DataFrame({
    'Feature': x_train.columns,
    'After L1 Regularization': lasso_cv.coef_
})
coefficients_after_l1

              Feature  After L1 Regularization
0           vendor_id                 0.027118
1    pickup_longitude                 3.220476
2     pickup_latitude                -3.084261
3   dropoff_longitude                 3.329882
4    dropoff_latitude                -2.843074
5  store_and_fwd_flag                 0.099174
6         day_of_week                -0.010677
7         hour_of_day                 0.005444

In [133]:
y_pred = lasso_cv.predict(x_test)

In [134]:
mean_absolute_percentage_error(y_test, y_pred)

0.09490445233744212

In [135]:
# create an array with 20 numbers equllay spaced between 0 to 10
alphas = np.linspace(0, 10, 20)
alphas

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [115]:
# Initialize ElasticNetCV to find the best alpha and l1_ratio
elastic_net_cv = ElasticNetCV(alphas=alphas, cv=10, max_iter=10000, l1_ratio=[.1, .5, .7, .9, .95, .99, 1])
elastic_net_cv.fit(x_train, y_train)

c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.301e+05, tolerance: 2.864e+01
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.300e+05, tolerance: 2.863e+01
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.299e+05, tolerance: 2.862e+01
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.295e+05, tolerance: 2.856e+01
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.301e+05, tolerance: 2.863e+01
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.302e+05, tolerance: 2.864e+01
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.300e+05, tolerance: 2.863e+01
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.299e+05, tolerance: 2.862e+01
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.295e+05, tolerance: 2.856e+01
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.301e+05, tolerance: 2.863e+01
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.302e+05, tolerance: 2.864e+01
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.300e+05, tolerance: 2.863e+01
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.299e+05, tolerance: 2.862e+01
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.295e+05, tolerance: 2.856e+01
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.301e+05, tolerance: 2.863e+01
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\RuchitaMotwani\.virtualenvs\Foundational_ML_Algorithams-RKBdPIqP\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:701: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(

ElasticNetCV(alphas=array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ]),
             cv=10, l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1],
             max_iter=10000)

In [116]:
# retrieve the best alpha and l1_ratio
best_alpha_enet = elastic_net_cv.alpha_
best_l1_ratio = elastic_net_cv.l1_ratio_

# print the l1_ratio and best_alpha value
(best_l1_ratio, best_alpha_enet)

(np.float64(0.5), np.float64(0.0))

In [117]:
# R-squared scores for the Ridge model
r2_train_enet = elastic_net_cv.score(x_train, y_train)
r2_test_enet = elastic_net_cv.score(x_test, y_test)

r2_train_enet, r2_test_enet

(0.09134180404880843, 0.09127589373212786)

In [118]:
y_pred = elastic_net_cv.predict(x_test)

In [120]:
mean_absolute_percentage_error(y_test, y_pred)

0.09490445233744212

### Conclusion
After trying out different techniques,
- Decision Tree model with max_depth=16 and min_sample_leaf=11 works best