### Here, we are building a decision tree classification model on the healthcare dataset, to see whether a person is healthy or not.
- Checking for class imbalance
- Analyzing feature importance
- Hyper-parameter tuning - max_depth, min_samples_leaf

In [61]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, f1_score
import numpy as np

In [ ]:
df = pd.read_csv("./data/Healthcare_Dataset_Preprocessed_(1).csv")

In [3]:
df.head()

,Age,BMI,Blood_Pressure,Cholesterol,Glucose_Level,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,...,Diet,MentalHealth,PhysicalActivity,MedicalHistory,Allergies,Diet_Type_Vegan,Diet_Type_Vegetarian,Blood_Group_AB,Blood_Group_B,Blood_Group_O
0,2.0,26.0,111.0,198.0,99.0,72.0,4.0,1.0,5.0,5.0,...,1,2,1,0,1,False,True,True,False,False
1,8.0,24.0,121.0,199.0,103.0,75.0,2.0,1.0,2.0,9.0,...,1,2,1,2,2,False,False,True,False,False
2,81.0,27.0,147.0,203.0,100.0,74.0,10.0,-0.0,5.0,1.0,...,2,0,0,1,0,True,False,False,False,False
3,25.0,21.0,150.0,199.0,102.0,70.0,7.0,3.0,3.0,3.0,...,1,2,1,2,0,True,False,False,True,False
4,24.0,26.0,146.0,202.0,99.0,76.0,10.0,2.0,5.0,1.0,...,2,0,2,0,2,False,True,False,True,False

In [4]:
df.describe()

,Age,BMI,Blood_Pressure,Cholesterol,Glucose_Level,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,Target,Smoking,Alcohol,Diet,MentalHealth,PhysicalActivity,MedicalHistory,Allergies
count,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000
mean,33.806786,25.660697,130.382658,199.091528,100.225678,73.613782,6.951409,1.892345,3.580899,4.382134,0.521416,0.990470,0.995183,1.005864,0.998429,1.003351,1.004713,0.989318
std,24.566473,1.942369,27.878476,1.969234,2.157999,1.681538,2.352152,1.378714,1.622874,2.078593,0.499567,0.815521,0.816653,0.815877,0.821844,0.808800,0.813506,0.815699
min,0.000000,19.000000,22.000000,192.000000,93.000000,67.000000,-0.000000,-0.000000,-0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,14.000000,24.000000,113.000000,198.000000,99.000000,73.000000,5.000000,1.000000,2.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,29.000000,26.000000,134.000000,199.000000,100.000000,74.000000,7.000000,2.000000,4.000000,4.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
75%,50.000000,27.000000,150.000000,200.000000,102.000000,75.000000,9.000000,3.000000,5.000000,6.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000
max,100.000000,32.000000,225.000000,207.000000,107.000000,80.000000,14.000000,8.000000,10.000000,12.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000

In [5]:
df.dtypes

Age                     float64
BMI                     float64
Blood_Pressure          float64
Cholesterol             float64
Glucose_Level           float64
Heart_Rate              float64
Sleep_Hours             float64
Exercise_Hours          float64
Water_Intake            float64
Stress_Level            float64
Target                    int64
Smoking                   int64
Alcohol                   int64
Diet                      int64
MentalHealth              int64
PhysicalActivity          int64
MedicalHistory            int64
Allergies                 int64
Diet_Type_Vegan            bool
Diet_Type_Vegetarian       bool
Blood_Group_AB             bool
Blood_Group_B              bool
Blood_Group_O              bool
dtype: object

In [8]:
X = df.drop("Target", axis=1)
y = df["Target"]

In [27]:
df["Target"].value_counts()

Target
1    4979
0    4570
Name: count, dtype: int64

### There is no significant class imbalance found

In [19]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify=y)

In [39]:
DT_model = DecisionTreeClassifier().fit(x_train, y_train)

In [40]:
DT_model.get_depth()

25

In [41]:
y_pred = DT_model.predict(x_test)

In [42]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.90      0.89      1371
           1       0.91      0.89      0.90      1494

    accuracy                           0.89      2865
   macro avg       0.89      0.89      0.89      2865
weighted avg       0.89      0.89      0.89      2865

In [29]:
#Retreiving the importance score of each feature
feature_imp = DT_model.feature_importances_

In [33]:
# Sorting the features by importance in descending order in a dataframe.
imp = pd.DataFrame({'Col_names': x_train.columns, 'Importance': np.round(feature_imp, 2)})\
.sort_values(by='Importance', ascending=False)
imp

               Col_names  Importance
1                    BMI        0.22
3            Cholesterol        0.18
2         Blood_Pressure        0.13
4          Glucose_Level        0.09
9           Stress_Level        0.09
6            Sleep_Hours        0.08
8           Water_Intake        0.05
0                    Age        0.04
5             Heart_Rate        0.04
7         Exercise_Hours        0.02
11               Alcohol        0.01
14      PhysicalActivity        0.01
16             Allergies        0.01
10               Smoking        0.00
13          MentalHealth        0.00
12                  Diet        0.00
15        MedicalHistory        0.00
17       Diet_Type_Vegan        0.00
18  Diet_Type_Vegetarian        0.00
19        Blood_Group_AB        0.00
20         Blood_Group_B        0.00
21         Blood_Group_O        0.00

In [34]:
# Calculating the cumulative sum of the 'Importance' column and store it in a new column called 'cum_imp'
imp['cum_imp'] = imp.Importance.cumsum()
imp

               Col_names  Importance  cum_imp
1                    BMI        0.22     0.22
3            Cholesterol        0.18     0.40
2         Blood_Pressure        0.13     0.53
4          Glucose_Level        0.09     0.62
9           Stress_Level        0.09     0.71
6            Sleep_Hours        0.08     0.79
8           Water_Intake        0.05     0.84
0                    Age        0.04     0.88
5             Heart_Rate        0.04     0.92
7         Exercise_Hours        0.02     0.94
11               Alcohol        0.01     0.95
14      PhysicalActivity        0.01     0.96
16             Allergies        0.01     0.97
10               Smoking        0.00     0.97
13          MentalHealth        0.00     0.97
12                  Diet        0.00     0.97
15        MedicalHistory        0.00     0.97
17       Diet_Type_Vegan        0.00     0.97
18  Diet_Type_Vegetarian        0.00     0.97
19        Blood_Group_AB        0.00     0.97
20         Blood_Group_B        0.00     0.97
21         Blood_Group_O        0.00     0.97

In [35]:
# Selecting the columns with cumulative importance exceeding 0.90 and create a list of column names to drop
drop_col = imp[imp.cum_imp >  0.90]['Col_names'].to_list()
drop_col

['Heart_Rate',
 'Exercise_Hours',
 'Alcohol',
 'PhysicalActivity',
 'Allergies',
 'Smoking',
 'MentalHealth',
 'Diet',
 'MedicalHistory',
 'Diet_Type_Vegan',
 'Diet_Type_Vegetarian',
 'Blood_Group_AB',
 'Blood_Group_B',
 'Blood_Group_O']

In [36]:
# Dropping the columns from X_train
x_train.drop(columns = drop_col, inplace = True)

# Dropping the columns from X_test
x_test.drop(columns = drop_col, inplace = True)

In [43]:
DT_model = DecisionTreeClassifier().fit(x_train, y_train)

In [48]:
depth = DT_model.get_depth()
depth

25

In [45]:
y_pred = DT_model.predict(x_test)

In [47]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.90      0.89      1371
           1       0.91      0.89      0.90      1494

    accuracy                           0.90      2865
   macro avg       0.90      0.90      0.90      2865
weighted avg       0.90      0.90      0.90      2865

### We can see, there is slight increase in the overall model performance

In [59]:
max_depth_list = list(range(depth, 0, -2))

In [60]:
max_depth_list

[25, 23, 21, 19, 17, 15, 13, 11, 9, 7, 5, 3, 1]

In [62]:
for d in max_depth_list:
    model = DecisionTreeClassifier(max_depth=d, random_state=42).fit(x_train, y_train)
    
    y_pred_train = model.predict(x_train)

    y_pred = model.predict(x_test)

    print(f"| Depth - {d} | Train F1 score = {f1_score(y_train, y_pred_train)} | Test F1 score = {f1_score(y_test, y_pred)}")

| Depth - 25 | Train F1 score = 1.0 | Test F1 score = 0.8999660902000678
| Depth - 23 | Train F1 score = 0.9998565073898694 | Test F1 score = 0.8996610169491526
| Depth - 21 | Train F1 score = 0.9985656913367756 | Test F1 score = 0.8989830508474577
| Depth - 19 | Train F1 score = 0.9962654409652398 | Test F1 score = 0.8993561504574721
| Depth - 17 | Train F1 score = 0.9903721799109068 | Test F1 score = 0.9030077728962488
| Depth - 15 | Train F1 score = 0.9823504089539389 | Test F1 score = 0.9067025934658134
| Depth - 13 | Train F1 score = 0.9689134224288205 | Test F1 score = 0.9004771642808452
| Depth - 11 | Train F1 score = 0.9505614700306256 | Test F1 score = 0.8957765667574932
| Depth - 9 | Train F1 score = 0.9267889149317524 | Test F1 score = 0.8936995153473344
| Depth - 7 | Train F1 score = 0.8896839594514013 | Test F1 score = 0.8622377622377623
| Depth - 5 | Train F1 score = 0.8727420888224908 | Test F1 score = 0.8623096446700508
| Depth - 3 | Train F1 score = 0.8363125638406538 | Test F1 score = 0.8232823282328233
| Depth - 1 | Train F1 score = 0.7565765980240448 | Test F1 score = 0.7535269709543568

### We can see that, at depth=15, we are getting maximum score

In [63]:
# Dictionary to store the train and test F1 scores

train_scores = {}
test_scores = {}


# Fill the values in the below list and assign value to the variable!
min_sample_leaf_list = [15, 10, 5, 3]
depth = 15

# Loop through min_sample_leaf values and train the models
for min_sample_leaf in min_sample_leaf_list:
    
    # Initialize the Decision Tree model with the current min_samples_leaf value
    DT_model = DecisionTreeClassifier(min_samples_leaf=min_sample_leaf, max_depth= depth, random_state=42)
    
    # Train the model
    DT_model.fit(x_train, y_train)
    
    # Make predictions on the train dataset
    y_train_pred = DT_model.predict(x_train)

    # Make predictions on the test dataset
    y_test_pred = DT_model.predict(x_test)
    
    # Store the train F1 score in the dictionary with the min_sample_leaf as the key
    train_scores[min_sample_leaf] = f1_score(y_train, y_train_pred)
    
    # Store the test F1 score in the dictionary with the min_sample_leaf as the key
    test_scores[min_sample_leaf] = f1_score (y_test, y_test_pred)
    

# Print the train and test F1 scores for each model
for min_sample_leaf in min_sample_leaf_list:
    print(f"min_sample_leaf = {min_sample_leaf}|\
    Train Score = {train_scores[min_sample_leaf]:.3f} |\
    Test Score = {test_scores[min_sample_leaf]:.3f}")
    print('_'*65)

min_sample_leaf = 15|    Train Score = 0.915 |    Test Score = 0.885
_________________________________________________________________
min_sample_leaf = 10|    Train Score = 0.924 |    Test Score = 0.889
_________________________________________________________________
min_sample_leaf = 5|    Train Score = 0.942 |    Test Score = 0.906
_________________________________________________________________
min_sample_leaf = 3|    Train Score = 0.957 |    Test Score = 0.902
_________________________________________________________________